---
- name: DevOps local environment setup on Ubuntu 24.04 (WSL2)
  hosts: localhost
  become: true
  vars:
    user: "{{ lookup('env','USER') }}"
  roles:
    - common
    #- docker
    #- kubectl
    #- k9s
    #- helm
    #- terraform
    #- ohmyzsh
    #- nerdfonts
    #- lazyvim
    #- tmux
    #- terminator
